// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresql

import (
	"time"

	"github.com/google/uuid"
)

type BoardStatus struct {
	ID        uuid.UUID
	StatusID  uuid.UUID
	Position  int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Card struct {
	ID        uuid.UUID
	Title     string
	Content   string
	StatusID  uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Status struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
