// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	Card(ctx context.Context, id uuid.UUID) (CardRow, error)
	CardsByStatus(ctx context.Context, id uuid.UUID) ([]CardsByStatusRow, error)
	DeleteCard(ctx context.Context, id uuid.UUID) error
	Statuses(ctx context.Context) ([]Status, error)
	UpsertCard(ctx context.Context, arg UpsertCardParams) error
}

var _ Querier = (*Queries)(nil)
