root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/simple-kanban"
cmd = "sqlc generate && templ generate && go build -o ./tmp/simple-kanban ."
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata", "internal/kanban/db"]
exclude_file = []
exclude_regex = ["_test.go", "_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = "DATABASE_URL='postgres://postgres@localhost:5432/postgres?search_path=public&sslmode=disable' ./tmp/simple-kanban"
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html", "sql"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = true

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
